theme: "hugo-PaperMod"
baseURL: http://example.org/
languageCode: en-us
title: knotes

params:
    homeInfoParams:
        Title: Hi there wave
        Content: Can be Info, links, about...
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
        
menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 50
        - identifier: tags
          name: tags
          url: /tags/
          weight: 60
        - identifier: search
          name: search
          url: /search/
          weight: 70
        - identifier: docs
          name: orthopaedics
          url: /docs/
          weight: 30
        - identifier: posts
          name: statistics
          url: /post/
          weight: 40