theme: "hugo-PaperMod"
baseURL: http://knotes2.netlify.app/
languageCode: en-us
title: knotes

params:
    homeInfoParams:
        Title: Kishore Puthezhath's official website
        Content: Include notes on Orthoaedics, research & statistics, medical education and general strifes
    ShowReadingTime: true
    ShowPostNavLinks: true
    author: ["Kishore Puthezhath"]
    
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
        
menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 50
        - identifier: tags
          name: tags
          url: /tags/
          weight: 60
        - identifier: search
          name: search
          url: /search/
          weight: 70
        - identifier: blog
          name: blog
          url: /blog/
          weight: 30
        - identifier: docs
          name: orthopaedics
          url: /docs/
          weight: 30
        - identifier: posts
          name: statistics
          url: /post/
          weight: 40
          