theme: "hugo-PaperMod"
baseURL: http://knotes2.netlify.app/
languageCode: en-us
title: knotes

params:
    homeInfoParams:
        Title: Kishore Puthezhath's official website
        Content: Include notes on Orthoaedics, research & statistics, medical education and general strifes
    ShowReadingTime: true
    ShowPostNavLinks: true
    author: ["Kishore Puthezhath"]

    profileMode:
        enabled: true
        title: "kishore Puthezhath's official website" # optional default will be site title
        subtitle: "
        **Kishore Puthezhath MS Ortho, D Ortho, FACS (USA), FRCS (Tr & Orth)(Eng)** is a Professor (associate) of Orthopaedics 
        and Consultant Paediatric Orthopaedic Surgeon at the KUHS. 
        His research interests include Paediatric deformities,Biostatistics in `r`, 
        Bayesian statistics and competency-based medical education (CBME). 
        He leads the Paediatric Orthopaedics Surgery in a tertiary teaching hospital in Kerala."
        
        
    
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
        
menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 50
        - identifier: tags
          name: tags
          url: /tags/
          weight: 60
        - identifier: search
          name: search
          url: /search/
          weight: 70
        - identifier: blog
          name: blog
          url: /blog/
          weight: 30
        - identifier: docs
          name: orthopaedics
          url: /docs/
          weight: 30
        - identifier: posts
          name: statistics
          url: /post/
          weight: 40
          



          